[build]
builder = "nixpacks"

[deploy]
releaseCommand = "php artisan optimize:clear && php artisan migrate --force && php artisan storage:link && php artisan db:seed --class=SuperAdminSeeder --force"
[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"